#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo ' Styling, testing and building your project before commiting'

# Check Prettier
npm run check-format ||
{
    echo 'Prettier Check Failed. Run npm run format, add changes and try commit again'
    false;
}

#check ESLint
npm run check-lint ||
{
    echo "ESLint Check Failed. Make the required change listed above, add changes and try to commit again."
    false;
}

#check tsconfig
npm run check-types ||
{
    echo "Failed type check. Make the changes required above, add changes and try to commit again."
    false;
}

npm run build ||
{
    echo "Your build failed, view the errors above"
    false;
}

echo "Success Commit"